### ISSUE TITLE
Query about Caching if Bundled Fonts

### ISSUE THREAD

**Issue by karanmartian** [expo/native-component-list#11]
If I bundle my fonts as per the following, then do I need to again cache them using Font.loadAsync when App first starts or can I just use them directly like: import {Ionicons, MaterialIcons} from "@expo/vector-icons"; in my code without having to worry that the fonts will be ready.

"assetBundlePatterns": [
      "node_modules/@expo/vector-icons/fonts/FontAwesome.ttf",
      "node_modules/@expo/vector-icons/fonts/Ionicons.ttf",
      "node_modules/@expo/vector-icons/fonts/MaterialIcons.ttf",
      "node_modules/@expo/vector-icons/fonts/MaterialCommunityIcons.ttf"
    ]

**Comment by anp** [comment]
Hi! It's still a good idea to cache them in order to make development smooth in the client app. In standalone mode, caching them should be pretty close to instant since they're on disk at that point -- I wouldn't expect it to add significantly to your TTI but could be wrong.

FYI, the [forums](https://forums.expo.io) are a much better venue for these kinds of questions. Thanks!

**Comment by karanmartian** [comment]
Hi @anp thanks for this, will surely post in forums in future but just to finish on my thought since you answered here - Font.loadAsync(...Ionicons.font) will first look for the font from the disk correct if its already bundled in the standalone app and if not it will download it? Its an important thing for me to understand since I really want to bundle my assets and have the app cache those from the local bundled assets only and not download anything.
